run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - unused

issues:
  # 测试文件豁免 errcheck 和 unused
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unused

  # 显式排除通常不检查的返回值
  exclude-functions:
    - io.Copy
    - "encoding/json.Unmarshal"
    - "(*encoding/json.Encoder).Encode"
    - "(*encoding/json.Decoder).Decode"
    - fmt.Scanf
